test: modified test scripts to allow commandline arg for nargmax

diff --git a/test/test_stdcl/scripts/run_quick_tests.sh.in b/test/test_stdcl/scripts/run_quick_tests.sh.in
--- a/test/test_stdcl/scripts/run_quick_tests.sh.in
+++ b/test/test_stdcl/scripts/run_quick_tests.sh.in
@@ -7,7 +7,8 @@ run_test() {
 	for (( i=0; i<$ndev; i++ ))
 	do 
 		printf "%-68s" "$1 $2 $3 (stddev $i)"
-		$1 --size $2 --blocksize $3 --dev $i >& /dev/null
+#		$1 --size $2 --blocksize $3 --dev $i >& /dev/null
+		$1 --size $2 --blocksize $3 --dev $i >& log.$1.stddev.$i
 		if [ $? -eq 0 ]; then
 			printf "%10s\n" "[pass]"
 		else 
@@ -20,7 +21,8 @@ run_test() {
 	for (( i=0; i<$ndev; i++ ))
 	do 
 		printf "%-68s" "$1 $2 $3 (stdcpu $i)"
-		$1 --size $2 --blocksize $3 --cpu $i >& /dev/null
+#		$1 --size $2 --blocksize $3 --cpu $i >& /dev/null
+		$1 --size $2 --blocksize $3 --cpu $i >& log.$1.stdcpu.$i
 		if [ $? -eq 0 ]; then
 			printf "%10s\n" "[pass]"
 		else 
@@ -33,7 +35,22 @@ run_test() {
 	for (( i=0; i<$ndev; i++ ))
 	do
 		printf "%-68s" "$1 $2 $3 (stdgpu $i)"
-		$1 --size $2 --blocksize $3 --gpu $i >& /dev/null
+#		$1 --size $2 --blocksize $3 --gpu $i >& /dev/null
+		$1 --size $2 --blocksize $3 --gpu $i >& log.$1.stdgpu.$i
+		if [ $? -eq 0 ]; then
+			printf "%10s\n" "[pass]"
+		else 
+			printf "%10s\n" "[failed]"
+		fi;
+	done
+
+	./getndev.x --acc >& /dev/null
+	ndev=$?
+	for (( i=0; i<$ndev; i++ ))
+	do
+		printf "%-68s" "$1 $2 $3 (stdacc $i)"
+#		$1 --size $2 --blocksize $3 --acc $i >& /dev/null
+		$1 --size $2 --blocksize $3 --acc $i >& log.$1.stdacc.$i
 		if [ $? -eq 0 ]; then
 			printf "%10s\n" "[pass]"
 		else 
@@ -52,7 +69,7 @@ if test "x$test_lib_opencl" = "xnot found"; then
    echo "libOpenCL.so not found, check LD_LIBRARY_PATH";
    exit -1;
 fi;
-if test "x$test_lib_stdcli" = "xnot found"; then
+if test "x$test_lib_stdcl" = "xnot found"; then
    echo "libstdcl.so not found, check LD_LIBRARY_PATH";
    exit -1;
 fi;
