build: add selection of compiler and model for libcoprthr

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -274,7 +274,7 @@ PACKAGE_STRING='coprthr 1.1'
 PACKAGE_BUGREPORT='support@browndeertechnology.com'
 
 ac_default_prefix=/usr/local/browndeer
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA BASH F90 ENABLE_CLGL ENABLE_CLETE ENABLE_DEBUG_LIBS ENABLE_CLTRACE ENABLE_CLLD ENABLE_LIBCOPRTHR ENABLE_LIBOCL ENABLE_NCPU OPENCL_INCLUDE OPENCL_LIB OPENCL_LIBNAME DEFAULT_OPENCL_PLATFORM libelf_inc libelf_lib LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA BASH F90 ENABLE_CLGL ENABLE_CLETE ENABLE_DEBUG_LIBS ENABLE_CLTRACE ENABLE_CLLD ENABLE_LIBCOPRTHR ENABLE_LIBOCL ENABLE_NCPU OPENCL_INCLUDE OPENCL_LIB OPENCL_LIBNAME DEFAULT_OPENCL_PLATFORM libelf_inc libelf_lib LIBCOPRTHR_CC LIBCOPRTHR_CXX LIBCOPRTHR_MODEL LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -830,6 +830,12 @@ Optional Packages:
   --with-opencl-lib=DIR   specify OpenCL lib path
   --with-fortran=PROG     Use fortran compiler PROG
   --with-libelf=DIR       specify path to libelf
+  --with-libcoprthr-cc=PROG
+                          use PROG for libcoprthr C compiler
+  --with-libcoprthr-cxx=PROG
+                          use PROG for libcoprthr C++ compiler
+  --with-libcoprthr-model=default|template|no-template
+                          select model for libcoprthr OCL compilation
 
 Some influential environment variables:
   CC          C compiler command
@@ -3186,7 +3192,6 @@ echo "$as_me: error: no fortran compiler specified" >&2;}
     else
     	F90=$withval
     fi;
-    echo $F90
 
 fi;
 
@@ -3281,6 +3286,74 @@ libelf_lib="-L$LIBELF_PATH/lib -lelf"
 ### XXX clean up this syntax - above - for setting paths and such -DAR
 
 
+### select C/C++ compilers for libcoprthr
+
+
+# Check whether --with-libcoprthr-cc or --without-libcoprthr-cc was given.
+if test "${with_libcoprthr_cc+set}" = set; then
+  withval="$with_libcoprthr_cc"
+
+    if test x$withval = xno; then
+         { { echo "$as_me:$LINENO: error: no C compiler specified" >&5
+echo "$as_me: error: no C compiler specified" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+    	LIBCOPRTHR_CC=$withval
+    fi;
+
+else
+   LIBCOPRTHR_CC=gcc
+fi;
+
+
+# Check whether --with-libcoprthr-cxx or --without-libcoprthr-cxx was given.
+if test "${with_libcoprthr_cxx+set}" = set; then
+  withval="$with_libcoprthr_cxx"
+
+    if test x$withval = xno; then
+         { { echo "$as_me:$LINENO: error: no C++ compiler specified" >&5
+echo "$as_me: error: no C++ compiler specified" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+    	LIBCOPRTHR_CXX=$withval
+    fi;
+
+else
+   LIBCOPRTHR_CXX=g++
+fi;
+
+
+# Check whether --with-libcoprthr-model or --without-libcoprthr-model was given.
+if test "${with_libcoprthr_model+set}" = set; then
+  withval="$with_libcoprthr_model"
+
+    if test x$withval = xtemplate; then
+    	LIBCOPRTHR_MODEL=$withval
+    elif test x$withval = xno-template; then
+    	LIBCOPRTHR_MODEL=$withval
+    elif test x$withval = xdefault; then
+    	LIBCOPRTHR_MODEL=$withval
+    else
+      { { echo "$as_me:$LINENO: error: invalid libcoprthr model selected" >&5
+echo "$as_me: error: invalid libcoprthr model selected" >&2;}
+   { (exit 1); exit 1; }; }
+    fi;
+
+else
+   LIBCOPRTHR_MODEL=default
+fi;
+
+if test x$enable_libcoprthr = xyes; then
+  echo LIBCOPRTHR_CC = $LIBCOPRTHR_CC
+  echo LIBCOPRTHR_CXX = $LIBCOPRTHR_CXX
+  echo LIBCOPRTHR_MODEL = $LIBCOPRTHR_MODEL
+fi;
+
+
+
+
+
+
 BASH=`which bash`
 
 
@@ -3296,6 +3369,10 @@ BASH=`which bash`
 
 #AC_SUBST(ENABLE_ATIGPU)
 #AC_SUBST(ENABLE_BDT_BUILTINS)
+
+
+
+
 
 
 
@@ -4073,6 +4150,9 @@ s,@OPENCL_LIBNAME@,$OPENCL_LIBNAME,;t t
 s,@DEFAULT_OPENCL_PLATFORM@,$DEFAULT_OPENCL_PLATFORM,;t t
 s,@libelf_inc@,$libelf_inc,;t t
 s,@libelf_lib@,$libelf_lib,;t t
+s,@LIBCOPRTHR_CC@,$LIBCOPRTHR_CC,;t t
+s,@LIBCOPRTHR_CXX@,$LIBCOPRTHR_CXX,;t t
+s,@LIBCOPRTHR_MODEL@,$LIBCOPRTHR_MODEL,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
